#%RAML 1.0 NamedExample
value:
  type: "CC"
  sub_type: "ICA"
  id: "80000072"
  name: "PERSONAL CHECKING"
  nick_name: "TEST"
  routing_number: "0031234"
  interest_rate: 5.43
  interest_earned_YTD: 121.34
  available_balance: 12765.92
  current_balance: 55728.83
  pending_balance: 55728.83
  available_credit: 1765.7
  credit_limit: 14000
  min_payment_amount: 126.54
  payment_due_date: "2019-04-29"
  purchase_apr: 19.99
  cash_apr: 21.99
  rewards_balance: 12000
  card_holder_name: "Spouse or child name"
  draw_period_end_date: "2019-04-29"
  rate_adjustment_date: "2019-04-29"
  num_payments_remaining: 124
  last_payment_date: "2019-04-29"
  next_payment_amount: 356.32
  outstanding_principal_balance: 123621.78
  outstanding_interest_balance: 18609.21
  original_balance: 250000
  change_in_value: -34.89
  change_in_percent: -2.65
  accrued_income: 343.87
  market_value: 7821.54
  estimated_income: 561.9
  total_cost_basis: 1281
  realized_gain_loss: 232.57
  unrealized_gain_loss: 2212.43
  unrealized_gain_loss_percent: 11.35
  security_holdings: 937.23
  cash_and_equivalent: 6884.31
  ticker_symbol: "CCNE"
  investment_name: "CNB Financial Corp"
  number_of_units: 37
  investment_cost: 5000
  asset_type: "IRA"