#%RAML 1.0 NamedExample
value:
  -
    type: "DP"
    total_balance: 76000.55
    accounts: 
      - id: "80000072"
        type_code: 41
        type_description: "Savings"
        name: "PERSONAL SAVINGS"
        nick_name: "Fun Fund"
        balance: 40000.34
        balance_as_of_date: "2019-03-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
      - id: "80000073"
        type_code: 340
        type_description: "Savings"
        name: "PUBLIC FUNDS SAVINGS"
        nick_name: "PUBLIC Fund"
        balance: 36000.21
        balance_as_of_date: "2019-02-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
  -
    type: "CC"
    total_balance: 8900
    accounts: 
      - id: "1234-5678-9012-3456"
        type_code: 3553
        type_description: "CASH BACK VISA SIGNATURE CARD"
        name: "CASH BACK VISA SIGNATURE CARD"
        nick_name: "The golden card"
        balance: 3500
        balance_as_of_date: "2019-03-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
      - id: "9876-5432-1098-7654"
        type_code: 2755
        type_description: "VISA PLATINUM CARD WITH REWARDS"
        name: "VISA PLATINUM CARD WITH REWARDS"
        nick_name: "Rewards Card"
        balance: 5400
        balance_as_of_date: "2019-02-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
  -  
    type: "LN"
    total_balance: 8908118
    accounts:
      - id: "54360000"
        type_code: 0
        type_description: "TERM LOAN TO BUSINESS"
        name: "TERM LOAN TO BUSINESS"
        nick_name: "My Term Loan"
        balance: 4564575
        balance_as_of_date: "2019-03-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
      - id: "99890000"
        type_code: 0
        type_description: "HOME EQUITY"
        name: "HOME EQUITY"
        nick_name: "Home sweet home"
        balance: 4343543
        balance_as_of_date: "2019-02-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
  -
    type: "INVMT"
    total_balance: 9000000
    accounts:
      - id: "324540000"
        type_code: 0
        type_description: "TBD"
        name: "TBD"
        nick_name: "TBD"
        balance: 4000000
        balance_as_of_date: "2019-03-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
      - id: "5355500000"
        type_code: 0
        type_description: "TBD"
        name: "TBD"
        nick_name: "TBD"
        balance: 5000000
        balance_as_of_date: "2019-02-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
  -  
    type: "TRST1"
    total_balance: 800000
    accounts: 
      - id: "676870000"
        type_code: 75
        type_description: "BOND TRUSTEESHIP"
        name: "CORPORATE TRUST"
        nick_name: "Bond Trust"
        balance: 500000
        balance_as_of_date: "2019-03-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
      - id: "67688600000"
        type_code: 92
        type_description: "SECURITIES ESCROW"
        name: "BUSINESS ESCROW"
        nick_name: "Sec Escrow"
        balance: 300000
        balance_as_of_date: "2019-02-25T10:41:00"
        created_date: "2019-01-22T14:53:38"
    
        
    

    